import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import ShowLayout from "@/components/layouts/ShowLayout";
import Hero1 from "@/components/Hero1/Hero1";
import Hero2 from "@/components/Hero2/Hero2";


export default function Heros() {
    return (
        <ShowLayout>
            <Head>
                <title>All Heros</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="component-title">Hero 1</div>
            <Hero1 />
            <div className="component-space"></div>
            <div className="component-title">Hero 2</div>
            <Hero2 />


        </ShowLayout>
    );
}
