import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import MainLayout from "@/components/layouts/MainLayout";
import Hero1 from "@/components/Hero1/Hero1";
import Hero2 from "@/components/Hero2/Hero2";
import ImageText__Columns from "@/components/ImageText__Columns/ImageText__Columns";
import MultiColumns from "@/components/MultiColumns/MultiColumns";
import Collections1 from "@/components/Collections1/Collections1";
import CollectionsSlider from "@/components/CollectionsSlider/CollectionsSlider";
import Reviews from "@/components/Reviews/Reviews";
import EmailCapture from "@/components/EmailCapture/EmailCapture";
import Products from "@/components/Products/Products";
import About from "@/components/About/About";
import GridColumns from "@/components/GridColumns/GridColumns";
import FAQ from "@/components/FAQ/FAQ";
import Accordian from "@/components/Accordian/Accordian";
import SingleProduct from "@/components/SingleProduct/SingleProduct";

import Footer from "@/components/Footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero2/>
      <ImageText__Columns/>
      <MultiColumns/>
      <Collections1/>
      <Reviews/>
      <EmailCapture/>

    </MainLayout>
  );
}
