import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import MainLayout from "@/components/layouts/MainLayout";
import Hero1 from "@/components/Hero1/Hero1";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  return (
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero1/>
    </MainLayout>
  );
}
